services:
  mongo_bp:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo_volume_bp:/data/db

volumes:
  mongo_volume_bp:
